data:
  neurons: &neurons
    val: 10
  time_steps: &time_steps 
    val: 1000
  no_samples: 100000
  jitter: 0.3
  min_isi: 1
  max_isi: 50
  min_rate: 2
  max_rate: 10
  only_even: True

  batch_size: 1024
  shuffle: True
  train_split: 0.7
  prefetch: 16

model:
  features: *neurons
  neurons_hidden_1: 128
  neurons_hidden_2: 64
  neurons_out: 2
  neuron_beta: 0.8
  time_steps: *time_steps
  return_spk: False

  # hyperparameters
  loss:
    # loss functions taken from snntorch
    # available losses: 
      # ce_temporal: [arg: invers]
      # ce_max_membrane: [arg: none]
      # ce_rate: [arg: none]
      # mse_temporal: [arg: tolerance]
      # mse_rate: [arg: correct_rate, incorrect_rate]
      # mse_membrane: [arg: on_target, off_target]
    type: "mse_rate"
    correct_rate: 0.5
    incorrect_rate: 0
    inverse: "reciprocal" # either reciprocal or negate, default: negate
    tolerance: 50
    off_target: 0
    on_target: 1

  accuracy:
    # available accuracies: rate, temporal
    type: "rate"
  
  optimiser:
    # available optimisers: adam
    type: "adam" 
    learning_rate: 0.0005
    betas: [0.9, 0.99]

  surrogate:
    # available in snntorch: 
    # atan [arg: alpha]
    # fast_sigmoid [arg: slope]
    # heavside [arg: None]
    # sigmoid [arg: slope]
    # spike_rate_escape [args: beta, slope]
    # straight_through [arg: None]
    # triangular [arg: threshold]
    type: "sigmoid"
    alpha: null
    beta: null
    slope: 25
    threshold: null

  # training parameters
  epochs: 5
  # partial training/testing in minibatches
  partial_training: -1
  partial_testing: -1

  # record hidden layers?
  samples: 10

  # fancy stuff (augmenting the forward pass within the model)
  move_fraction: 0.0
