config_data:
  DEBUG: False
  data_path: "data"
  to_memory: True
  filter_time: 10000
  time_window: 1000
  batch_size: 128
  worker: 5
  prefetch: 10

config_model:

  # available in snntorch: 
      # atan [arg: alpha]
      # fast_sigmoid [arg: slope]
      # heavside [arg: None]
      # sigmoid [arg: slope]
      # spike_rate_escape [arg: [beta, slope]]
      # straight_through [arg: None]
      # triangular [arg: threshold]
  
  # available in this code: 
      # super_spike_21 [arg: TODO]
  surrogate: "atan"
  surrogate_arg: [2]
  learning_rate: 0.03
  epochs: 1
  beta: 0.5 # of neurons

  # record hidden layers?
  record_train: False
  record_test: True


  # partial training in minibatches. to disable set to -1
  partial_training: 50
  DEBUG: False
  report_loss: True