config_data:
  seed: 42
  DEBUG: False
  data_path: "data"
  cache_path: "data/cache/"
  # run-specific name for the save files of the layer recordings
  identifier: null

  filter_time: 10000
  time_window: 1000
  batch_size: 64
  worker: 4
  prefetch: 10

  # available encodings: rate, latency, latency_timing
  target: "rate"


config_model:

  # hyperparameters
  loss:
    # loss functions taken from snntorch
    # available losses: 
      # ce_temporal: [arg: invers]
      # ce_rate: [arg: none]
      # mse_temporal: [arg: tolerance]
      # mse_rate: [arg: correct_rate, incorrect_rate]
    type: "ce_temporal"
    correct_rate: null
    inverse: "reciprocal"
    incorrect_rate: null
    tolerance: null

  accuracy:
    # available accuracies: rate, temporal
    type: "temporal"
  
  optimiser:
    # available optimisers: adam
    type: "adam" 
    learning_rate: 0.03
    betas: [0.9, 0.99]
  
  surrogate:
    # available in snntorch: 
    # atan [arg: alpha]
    # fast_sigmoid [arg: slope]
    # heavside [arg: None]
    # sigmoid [arg: slope]
    # spike_rate_escape [args: beta, slope]
    # straight_through [arg: None]
    # triangular [arg: threshold]
    type: "sigmoid"
    alpha: null
    beta: null
    slope: 25
    threshold: null

  # neuron configurations
  neuron:
    beta: 0.5 # of neurons

  # training parametres
  epochs: 1
  # partial training in minibatches. to disable set to -1
  partial_training: 50
  partial_testing: 10


  # record hidden layers?
  record_train: False
  record_test: True
  samples_per_class: 10

  DEBUG: False
  PROGRESS: False