config_data:
  DEBUG: True
  data_path: "data"
  to_memory: True
  filter_time: 10000
  time_window: 1000
  batch_size: 128
  worker: 5
  prefetch: 10

config_model:

  # available in snntorch: 
      # atan [arg: alpha]
      # fast_sigmoid [arg: slope]
      # heavside [arg: None]
      # sigmoid [arg: slope]
      # spike_rate_escape [arg: [beta, slope]]
      # straight_through [arg: None]
      # triangular [arg: threshold]
  
  # available in this code: 
      # super_spike_21 [arg: TODO]
  surrogate: "sigmoid"
  surrogate_arg: 25
  epochs: 25
  beta: 0.5