from imports import (
    NOW,
    NUMPY_RNG,
    TORCH_RNG,
    Figure,
    Path,
    ProcessPoolExecutor,
    Sequence,
    math,
    os,
    plt,
    torch,
    tqdm,
)
from imports import numpy as np

DEBUG: bool = False
CPU_COUNT: int = os.cpu_count() or 0

# function definition for parallel processing
def _task(
        generator: "DataGenerator",
        idx: int
    ) -> np.ndarray:
    # sample
    sample = generator._generate_sample(
        generator.isis[idx],
        generator.rates[idx]
    )
    # shuffle if needed
    if generator.shuffle > 0:
        sample = generator._shuffle(sample)
    return sample

class DataGenerator:
    def __init__(
        self,
        time_steps: int,
        shuffle: float = 0.0,
        neurons: int = 10,
        min_isi: int = 1,
        max_isi: int = 10,
        min_rate: int = 5,
        max_rate: int = 20,
        class_samples: int = 5000,
        retries: int = 5,
        precision: type[np.generic] = np.float32
    ):
        """
        Data Generator\n

        Heavily inspired by: 
        Yu, Z., Sun, P., & Goodman, D. F. (2025). 
        Beyond Rate Coding: Surrogate Gradients Enable Spike Timing Learning in Spiking Neural Networks.
        arXiv preprint arXiv:2507.16043.\n

        Class used to handle synthetic spike-data generation. 
        Data is generated by sampling an Inter-Spike-Interval (isi) and a rate.\n
        The rate defines how many spikes should be within the time_steps long sample by the formula 
        (rate * 2 * Time Steps) / 1000.\n

        Spike pairs (exactly one isi apart) are then placed in a random, non-overlapping manner during the sample time.
        Each neuron has independent spike trains, but the parameters within one sample stay the same.

        :param time_steps: Number of time steps for each sample
        :type time_steps: int, required
        :param shuffle: Fraction of spikes to shuffle, defaults to 0.0
        :type shuffle: float, optional
        :param neurons: Number of neurons in each sample, defaults to 10
        :type neurons: int, optional
        :param min_isi: Minimum inter-spike interval, defaults to 1
        :type min_isi: int, optional
        :param max_isi: Maximum inter-spike interval, defaults to 10
        :type max_isi: int, optional
        :param min_rate: Minimum firing rate, defaults to 5
        :type min_rate: int, optional
        :param max_rate: Maximum firing rate, defaults to 10
        :type max_rate: int, optional
        :param class_samples: Number of points to sample the parameters space from, defaults to 5000.
        :type class_samples: int, optional
        :param precision: Numpy data type precision for samples, defaults to np.float32
        :type precision: numpy.dtype, optional
        """

        self.time_steps = time_steps
        self.shuffle = shuffle
        self.neurons = neurons
        self._min_isi  = min_isi
        self._max_isi  = max_isi
        self._min_rate = min_rate
        self._max_rate = max_rate
        self._precision = precision
        self._retries = retries

        rates, isis, classes = self._get_class_assignments(class_samples)
        self.rates   = rates
        self.isis    = isis
        self.classes = classes


    def _get_class_assignments(
        self,
        no_samples: int = 3000
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Generate continuous (rate, isi) pairs with class assignment.

        Uses a linear boundary to assign classes:
        - Class 0: isi > slope * rate + intercept
        - Class 1: isi < slope * rate + intercept
        - Ignore: near the boundary (margin)
        """
        if no_samples % 2 == 1:
            raise ValueError(f"no_samples must be even. Got {no_samples}.")

        rates = NUMPY_RNG.uniform(
            self._min_rate,
            self._max_rate,
            int(no_samples * 1.5)   # oversampling, because of invalidation later
        )
        isis = NUMPY_RNG.uniform(
            self._min_isi,
            self._max_isi,
            int(no_samples * 1.5)   # oversampling, because of invalidation later
        )

        # define line to separate classes
        x0 = self._min_rate
        x1 = self._max_rate

        y0 = self._min_isi + (2/3) * (self._max_isi - self._min_isi)
        y1 = self._min_isi + (1/3) * (self._max_isi - self._min_isi)

        slope = (y1 - y0) / (x1 - x0)
        intercept = y0 - slope * x0

        line = (slope * rates + intercept)

        # margin around the line
        margin = 2.5
        boundary = np.abs(isis - line) <= margin


        # assign classes
        classes = np.zeros(int(no_samples * 1.5), dtype = np.int8)
        classes[isis > line + margin] = 1
        classes[isis < line - margin] = 0

        # map spaciatl corrdinates to features
        rates = self._linear_map_to_half_steps(
            rates,
            rates.min(), rates.max(),
            self._min_rate, self._max_rate,
            step = 0.1
        )
        isis = self._linear_map_to_half_steps(
            isis,
            isis.min(), isis.max(),
            self._min_isi, self._max_isi, 
            step = 1
        )

        # filter out samples generated in boundary zone if needed
        # exact amount of possible points is not relevant,
        # thus no limitation to only [no_samples]
        valid_mask = ~boundary
        rates = rates[valid_mask]
        isis = isis[valid_mask]
        classes = classes[valid_mask]

        # check that nothing went wrong
        assert rates.shape == isis.shape and rates.shape == classes.shape
        return rates, isis, classes

    def _generate_sample(
        self,
        isi: int,
        rate: int
    ) -> np.ndarray:

        """
        Generate a Sample. \n
        A sample has the shape [time_steps, neurons].
        For each neuron there will be set rate * (time_steps/1000) * 1/2 spike pairs.
        The time between the spikes is set by isi.
        The spike pairs do not overlap.

        :param isi: Inter-Spike-Interval; How long the time between two spikes should last.
        :type isi: int, required
        :param rate: Rate; How many spikes should there be in this sample.
        :type rate: int, required
        :returns: Numpy array containing spike trains for each neuron. Shape [time_steps, neurons]
        :rtype: numpy.ndarray
        """

        # calculate number of spike-pairs, given in [source]
        spk_pairs = int(np.round(
            rate * (self.time_steps / 1000)
        ).item())
        # cast isi to be an integer
        isi = max(1, int(isi))

        # preallocate the resulting array
        out = np.zeros(
            shape = (self.time_steps, self.neurons),
            dtype = self._precision,
        )

        for i in range(self.neurons):

            success = False
            for j in range(self._retries):
                # array with valid start positions of a spike pair
                mask = np.ones(
                    (self.time_steps - isi,),
                    dtype = bool
                )
                mask_max_idx = mask.shape[0] - 1

                # save samples somewhere
                all_samples = np.zeros(
                    (0,),
                    dtype = np.int16    # for some reason int8 are slower
                )

                cur_no = 0
                while cur_no < spk_pairs:
                    # break if no valid positions are left
                    if mask.sum() == 0:
                        success = False
                        break


                    # select a bunch of random starting positions
                    sample = np.flatnonzero(mask)
                    NUMPY_RNG.shuffle(
                        sample
                    )
                    sample = sample[:spk_pairs - cur_no]

                    # sort them if this is the first iteration
                    if len(all_samples) == 0:
                        sample.sort()

                    # put them in the sorted all_samples array
                    idx = np.searchsorted(all_samples, sample)
                    all_samples = np.insert(all_samples, idx, sample)

                    # check if there are any values created that are in invalid positions
                    tmp_mask = np.r_[True, np.diff(all_samples) >= isi]
                    all_samples = all_samples[tmp_mask]

                    # update cur_no and mask
                    cur_no = all_samples.shape[0]

                    # hacky way of setting the mask to wrong
                    idx = sample[:,None] + np.arange(isi)
                    mask[idx.clip(max = mask_max_idx)] = False
                    success = True

                if success:
                    # set samples
                    out[all_samples, i] = 1
                    out[all_samples + isi, i] = 1
                    break

                if j >= self._retries - 1:
                    print("Warning: Did not generate all spike pairs, no valid positions left!")
                    print(f"ISI: {isi} and Rate {rate}. Wanted to generate {spk_pairs} spike pairs, but could only fit {len(all_samples)}.\n")


        return out

    def _shuffle(
        self,
        sample: np.ndarray,
    ) -> np.ndarray:

        """
        Shuffle the spikes of each neuron-specific spike train.\n
        Moves the specified fraction of spikes (self.shuffle) to a random time step.
        This breaks the inter-spike-interval of some spike pairs.

        :param sample: Sample with sparse spikes.
        :type sample: numpy.ndarray
        :returns: Sample with perturbed spike-timings
        :rtype: numpy.ndarray
        """

        # get indices where spikes are, and where they aren't 
        spikes = np.nonzero(sample)
        valid_to = np.nonzero(sample == 0)

        for neuron in range(sample.shape[1]):
            # create a mask for each neuron
            # that is because spikes should not change their associated neuron
            spk_mask = spikes[1] == neuron
            move_mask = valid_to[1] == neuron
            to_move = math.ceil(spk_mask.sum() * self.shuffle)

            # jumble spikes and select the first to_move ones 
            # (same as random choice without replacement, but faster)
            selected_spikes = NUMPY_RNG.permutation(
                spikes[0][spk_mask]
            )[:to_move]

            # generate new position from valid ones
            new_positions = NUMPY_RNG.permutation(
                valid_to[0][move_mask]
            )[:to_move]

            # move spikes (or remove the original positions of the spikes moved)
            # (and add spikes where they got moved to)
            sample[selected_spikes, neuron] -= 1
            sample[new_positions, neuron] += 1

        return sample


    @staticmethod
    def _linear_map_to_half_steps(
        value: np.ndarray,
        old_min: float,
        old_max: float,
        new_min: float,
        new_max: float,
        step: float = 1.0
    ) -> np.ndarray:
        """
        Map values from one range to another with step discretization.
        """
        mapped = (value - old_min) / (old_max - old_min) \
                * (new_max - new_min) + new_min
        stepped = np.round(mapped / step) * step
        return np.clip(stepped, new_min, new_max)

    def generate_samples(
        self,
        no_samples: int = 3000,
        workers: int | None = None
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Generates samples and labels alongside them.\n

        A sample has the shape [time_steps, neurons].
        For each neuron there will be set rate * (time_steps/1000) spike pairs.
        The time between the spikes is set by isi.
        The spike pairs do not overlap.\n

        Does NOT shuffle.

        :param no_samples: Numbers of samples to generate, defaults to 3000
        :type no_samples: int, optional
        :returns: Tuple of arrays [data, labels]
        :rtype: tuple[numpy.ndarray, numpy.ndarray]
        """
        if no_samples % 2 == 1:
            raise ValueError(f"no_samples must be even. Got {no_samples}.")

        samples_per_class = math.ceil(no_samples / 2)

        if DEBUG:
            print(f"Samples:\n Type: {type(no_samples)}\n Actual: {no_samples}")
            print(f"Neurons:\n Type: {type(self.neurons)}\n Actual: {self.neurons}")
            print(f"TimeSteps:\n Type: {type(self.time_steps)}\n Actual: {self.time_steps}")

        # preallocate arrays
        samples = np.empty(
            shape = (no_samples, self.time_steps, self.neurons),
            dtype = self._precision
        )
        labels  = np.empty(
            shape = (no_samples,),
            dtype = np.uint8
        )

        for i in range(2):
            # generate samples by drawing an index from the class assignment array
            # where the class is the specified one 
            indices = NUMPY_RNG.choice(
                np.nonzero(self.classes == i)[0],
                size = samples_per_class,
                replace = True
            )

            if workers is not None:
                # fancy multithreading
                with ProcessPoolExecutor(max_workers = workers) as executor:
                    # create todolist
                    todos = [
                        executor.submit(_task, self, i) for i in indices
                    ]

                    for j, future in tqdm.tqdm(
                        iterable = enumerate(todos),
                        total = len(todos),
                        desc = f"Generating Samples for Class {i}"
                    ):
                        # get result
                        sample = future.result()

                        # store samples and labels
                        # i * len(indices) specifies the initial offset from the array start
                        # as in: is it class one (saved from 0 - len(indices)) or is it class two
                        # which is saved from len(indices) to -1
                        # the +j is the offset from the start of each class.
                        samples[i * samples_per_class + j] = sample
                    labels[i * samples_per_class : (i+1) * samples_per_class] = i


            else:
                # standard single-threaded
                for j, idx in tqdm.tqdm(
                        iterable = enumerate(indices),
                        total = len(indices),
                        desc = f"Generating Samples for Class {i}"
                    ):
                    # generate sample and save
                    # more info see above
                    sample = _task(self, idx)
                    samples[i * samples_per_class + j] = sample
                labels[i * samples_per_class : (i+1) * samples_per_class] = i


            # for j, idx in tqdm.tqdm(enumerate(indices)):
            #     # generate sample with self.isis[idx] and self.rates[idx]
            #     # this works, because all arrays got flattened
            #     sample = self._generate_sample(
            #         isi = int(self.isis[idx]),
            #         rate = int(self.rates[idx])
            #     )

            #     # some debug print statements for roughly checking whether the shuffling worked
            #     if DEBUG:
            #         sample_sum = [sample[:,i].sum() for i in range(self.neurons)]
            #         print(f"Rate: {self.rates[idx]}, ISI: {self.isis[idx]}, Class: {self.classes[idx]}")
            #         print(f"Sample sum per neuron: {sample_sum}.\n" +
            #               f"Expected sum per neuron: {self.rates[idx] * self.neurons * (self.time_steps / 1000) * 2}")

            #     if self.shuffle > 0:
            #         sample = self._shuffle(
            #             sample = sample,
            #         )

            #         if DEBUG:
            #             print("After shuffling:\n" +
            #                   f"Sample sum per neuron: {[sample[:,i].sum() for i in range(self.neurons)]}.\n" +
            #                   "Expected to match sample sum per neuron.\n" +
            #                   f"{[sample[:,i].sum() for i in range(self.neurons)] == sample_sum}"               # type: ignore
            #                   )


            #     samples[i * len(indices) + j] = sample
            # labels[i * len(indices) : (i + 1) * len(indices)] = i

        return samples, labels

    def generate_dataset(
        self,
        no_samples: int = 3000,
        batch_size: int = 256,
        shuffle: bool = True,
        train_split: float = 0.8,
        prefetch: int = 16,
        workers: int = max(2, CPU_COUNT - 4)
    ) -> Sequence[torch.utils.data.DataLoader]:

        """
        Generate PyTorch DataLoader(s) from synthetic spike data.\n

        Creates a DataLoader or pair of DataLoaders (train/test) containing synthetic spike data.
        Data is generated using the generate_samples() method and wrapped in PyTorch Dataset/DataLoader 
        classes for efficient training.

        :param no_samples: Number of samples to generate, defaults to 3000
        :type no_samples: int, optional
        :param batch_size: Number of samples per batch, defaults to 256
        :type batch_size: int, optional
        :param shuffle: Whether to shuffle the data during training, defaults to True
        :type shuffle: bool, optional
        :param train_split: Fraction of data to use for training (0 for no split), defaults to 0.8
        :type train_split: float, optional
        :param prefetch: Number of batches to prefetch, defaults to 16
        :type prefetch: int, optional
        :param workers: Number of worker processes for data loading, defaults to max(2, CPU_COUNT-4)
        :type workers: int, optional

        :returns: Single DataLoader if train_split=0, otherwise tuple of (train_loader, test_loader)
        :rtype: Union[torch.utils.data.DataLoader, tuple[torch.utils.data.DataLoader, torch.utils.data.DataLoader]]

        :raises ValueError: If train_split > 1
        """

        if train_split > 1:
            raise ValueError(f"train_split is too large. Can be at most 1. Actual: {train_split}")

        # generate the samples
        data, labels = self.generate_samples(
            no_samples = no_samples,
            workers = workers
        )

        # put them in a dataset with the correct dtype
        ds = torch.utils.data.TensorDataset(
            torch.from_numpy(data),
            torch.from_numpy(labels.astype(np.int64))
        )

        # function for returning the batches with time_first
        def _time_first_batch(batch):
            xs, ys = zip(*batch)

            xs = torch.stack(xs).permute(1, 0, -1).contiguous()
            ys = torch.stack(ys)

            return xs, ys

        if train_split == 0:
            # and make a nice dataloader out of it
            loader = (torch.utils.data.DataLoader(
                dataset = ds,
                batch_size = batch_size,
                shuffle = shuffle,
                drop_last = True,
                num_workers = workers,
                pin_memory = True,
                prefetch_factor = prefetch,
                in_order = False,
                collate_fn = _time_first_batch
            ),)
        else:
            # split the dataset if specified
            train, test = torch.utils.data.random_split(
                ds,
                [train_split, 1 - train_split],
                generator = TORCH_RNG
            )

            # and again Dataloader
            train_loader = torch.utils.data.DataLoader(
                dataset = train,
                batch_size = batch_size,
                shuffle = shuffle,
                drop_last = True,
                num_workers = workers,
                pin_memory = True,
                prefetch_factor = prefetch,
                in_order = False,
                collate_fn = _time_first_batch

            )
            test_loader = torch.utils.data.DataLoader(
                dataset = test,
                batch_size = batch_size,
                shuffle = shuffle,
                drop_last = True,
                num_workers = workers,
                pin_memory = True,
                prefetch_factor = prefetch,
                in_order = False,
                collate_fn = _time_first_batch
            )
            loader = (train_loader, test_loader)
        return loader

    def visualise_classes(
        self,
        save: bool = True
    ) -> Figure:

        cls = 1
        isi = 32
        rate = 4
        tmp_shuffle = 0.3

        backup_shuffle = self.shuffle
        self.shuffle = tmp_shuffle

        # fixed sample:
        sample = self._generate_sample(
            isi = isi,
            rate = rate
        )
        shuffled_sample = self._shuffle(
            sample.copy()
        )

        fig, axes = plt.subplot_mosaic(
            mosaic = [
                ["classes", "spikes"],
                ["classes", "shuffled"]
            ],
            figsize = (12,6),
            dpi = 200,
            height_ratios = [1,1],
            width_ratios = [2,5]
        )

        mask = (self.classes != -1).nonzero()
        scatter = axes["classes"].scatter(
            x = self.rates[mask],
            y = self.isis[mask],
            c = self.classes[mask],
        )
        axes["classes"].set_title("Class Assignment")
        axes["classes"].set_xlabel("Rates")
        axes["classes"].set_ylabel("ISIs")
        axes["classes"].legend(
            *scatter.legend_elements(),
            loc = "upper right",
            title = "Classes"
        )

        X, Y = sample.nonzero()
        axes["spikes"].scatter(
            x = X,
            y = Y,
            marker = "|"
        )
        axes["spikes"].set_title(f"Sample of Class {cls} (ISI: {isi}, Rate: {rate})")
        axes["spikes"].set_xlabel("Time Steps")
        axes["spikes"].set_xlim(left = 0, right = self.time_steps)
        axes["spikes"].set_ylabel("Neurons")

        X, Y = shuffled_sample.nonzero()
        axes["shuffled"].scatter(
            x = X, 
            y = Y,
            marker = "|"
        )
        axes["shuffled"].set_title(f"Shuffled Sample of Class {cls} (ISI: {isi}, Rate: {rate}, shuffle: {self.shuffle})")
        axes["shuffled"].set_xlabel("Time Steps")
        axes["shuffled"].set_xlim(left = 0, right = self.time_steps)
        axes["shuffled"].set_ylabel("Neurons")

        fig.tight_layout()

        if save:
            # create directory and save into it
            os.makedirs(
                os.path.join(
                    Path(__file__).parent.parent,
                    "img",
                    NOW
                ),
                exist_ok = True
            )

            fig.savefig(
                os.path.join(
                    Path(__file__).parent.parent,
                    "img",
                    NOW,
                    "class-assignment.pdf"
                ),
                format = "pdf"
            )

        self.shuffle = backup_shuffle
        return fig


def vis(
        sample: np.ndarray,
        label: int = 0
    ) -> None:
    plt.spy(
        sample.T,
        marker = ".",
        markersize = 10,
        aspect = "auto"
    )
    plt.xlabel("Time step")
    plt.ylabel("Neuron")
    plt.title("Label: " + str(label))